# Dockerfile to test lamda_function in local
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
        && rm requirements.txt
    
COPY lambda_function.py .

CMD ["python", "-m", "lambda_function"]